src/UNEXCA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('sga.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

src/sga/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # urls generales
    path('', views.home, name='home'),
    path('perfil/', views.Perfil.as_view(), name='perfil'),

    # urls para docentes
    path('u/2/clases/', views.DocenteClases.as_view(), name='docente_clases'),
    path('u/2/matricula/', views.DocenteMatricula.as_view(),
         name='docente_matricula'),
    path('u/2/matricula/<int:clase>',
         views.DocenteMatricula.as_view(), name='docente_matricula_clase'),

    # urls para alumnos
    path('u/3/clases/', views.AlumnoClases.as_view(), name='alumno_clases'),
    path('u/3/clases/inscribir/', views.AlumnoInscribirClase.as_view(),
         name='alumno_inscribir_clase'),
    path('u/3/clases/<int:pk>/retirar/', views.AlumnoRetirarClase.as_view(),
         name='alumno_retirar_clase'),
    path('u/3/solicitudes/', views.AlumnoSolicitudes.as_view(),
         name='alumno_solicitudes'),
]

src/sga/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Usuario(AbstractUser):
    roles = [
        (1, 'Administrador'),
        (2, 'Docente'),
        (3, 'Alumno'),
    ]

    username = models.IntegerField('cédula', unique=True)
    rol = models.IntegerField(
        'rol', choices=roles, default=roles[2][0])
    last_name = models.CharField('apellidos', max_length=150)
    first_name = models.CharField('nombres', max_length=150)

    REQUIRED_FIELDS = ['rol', 'last_name', 'first_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'.strip()

    def get_telefono(self):
        telefono = self.datosusuario.telefono
        return telefono if telefono else '---'

    def get_correo(self):
        correo = self.email
        return correo if correo else '---'


class Estado(models.Model):
    nombre = models.CharField('estado', max_length=100)

    def __str__(self):
        return str(self.nombre)

    class Meta:
        verbose_name = 'estado'
        verbose_name_plural = 'estados'


class DatosUsuario(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    telefono = models.CharField('teléfono', max_length=50, blank=True)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, blank=True)
    direccion = models.CharField('dirección', max_length=50, blank=True)

    def __str__(self):
        return f'{self.usuario}'

    class Meta:
        verbose_name = 'dato de usuario'
        verbose_name_plural = 'datos de usuarios'


class Carrera(models.Model):
    nombre = models.CharField('carrera', max_length=30, unique=True)

    def __str__(self):
        return f'{self.nombre}'

    class Meta:
        verbose_name = 'carrera'
        verbose_name_plural = 'carreras'


class Seccion(models.Model):
    codigo = models.CharField('código de sección', max_length=10)
    carrera = models.ForeignKey(
        Carrera, on_delete=models.CASCADE, verbose_name='carrera', default='')

    def __str__(self):
        return f'{self.carrera} {self.codigo}'

    class Meta:
        verbose_name = 'sección'
        verbose_name_plural = 'secciones'


class Materia(models.Model):
    nombre = models.CharField('materia', max_length=30, unique=True)

    def __str__(self):
        return f'{self.nombre}'

    class Meta:
        verbose_name = 'materia'
        verbose_name_plural = 'materias'


class Clase(models.Model):
    dias_de_la_semana = [
        ('lun', 'Lunes'),
        ('mar', 'Martes'),
        ('mie', 'Miércoles'),
        ('jue', 'Jueves'),
        ('vie', 'Viernes'),
        ('sab', 'Sábado')
    ]

    materia = models.ForeignKey(
        Materia, on_delete=models.CASCADE, verbose_name='materia')
    docente = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, limit_choices_to={'rol': 2},
        verbose_name='docente')
    seccion = models.ForeignKey(
        Seccion, on_delete=models.CASCADE, verbose_name='sección')
    dia = models.CharField(
        'días', max_length=50, choices=dias_de_la_semana)
    hora_inicio = models.TimeField('hora de inicio')
    hora_fin = models.TimeField('hora de fin')
    aula = models.IntegerField('aula')

    def __str__(self):
        return f'{self.materia} ({self.seccion}) - {self.docente}'

    class Meta:
        verbose_name = 'clase'
        verbose_name_plural = 'clases'


class Inscripcion(models.Model):
    alumno = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, limit_choices_to={'rol': 3},
        verbose_name='alumno')
    clase = models.ForeignKey(
        Clase, on_delete=models.CASCADE, verbose_name='clase')

    def __str__(self):
        return f'{self.alumno} - {self.clase}'

    class Meta:
        verbose_name = 'inscripción de materia'
        verbose_name_plural = 'inscripciones de materias'

src/sga/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from . import models


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = models.CustomUser
        fields = ('id', 'password')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = models.CustomUser
        fields = ('id', 'password')

src/sga/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import View, ListView, CreateView, DeleteView, TemplateView
from django.http import Http404
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from . import models


class RoleTestMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.rol == self.required_role

    def handle_no_permission(self):
        raise Http404('Página no encontrada')


@login_required
def home(request):
    match request.user.rol:
        case 1:
            return redirect('admin/')
        case 2:
            return redirect('docente_clases')
        case 3:
            return redirect('alumno_clases')
        case _:
            return redirect('login')


class DocenteClases(RoleTestMixin, ListView):
    required_role = 2
    model = models.Clase
    template_name = 'user/teacher/classes.html'

    def get_queryset(self):
        return models.Clase.objects.filter(docente=self.request.user)


class DocenteMatricula(RoleTestMixin, View):
    required_role = 2
    template_name = 'user/teacher/enrollments.html'

    def get(self, request, clase=None):
        clases = models.Clase.objects.filter(docente=request.user)
        context = {'clases': clases}

        if clase is not None:
            if not clases.filter(id=clase):
                raise Http404('Clase no encontrada')
            else:
                alumnos = models.Inscripcion.objects.filter(clase__id=clase)
                context['inscripcion_list'] = alumnos
                context['clase_id'] = clase
                clase_model = models.Clase.objects.get(id=clase)
                clase_display = f'{clase_model.materia} ({clase_model.seccion})'
        else:
            clase_display = 'Seleccionar materia'
        context['clase_display'] = clase_display

        return render(request, self.template_name, context)


class AlumnoClases(RoleTestMixin, ListView):
    required_role = 3
    model = models.Inscripcion
    template_name = 'user/student/classes.html'

    def get_queryset(self):
        return models.Inscripcion.objects.filter(alumno=self.request.user)


class AlumnoInscribirClase(RoleTestMixin, CreateView):
    required_role = 3
    model = models.Inscripcion
    template_name = 'form_simple.html'
    fields = ['clase']
    success_url = reverse_lazy('alumno_clases')

    def form_valid(self, form):
        form.instance.alumno = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['clase'].queryset = models.Clase.objects.exclude(
            inscripcion__alumno=self.request.user)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_name'] = 'Inscribir clase'
        return context


class AlumnoRetirarClase(RoleTestMixin, DeleteView):
    required_role = 3
    model = models.Inscripcion
    success_url = reverse_lazy('alumno_clases')


class AlumnoSolicitudes(RoleTestMixin, TemplateView):
    required_role = 3
    template_name = 'user/student/requests.html'


class Perfil(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'

src/sga/templates/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} - UNEXCA</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon_16x16.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon_32x32.png' %}">
    <link rel="icon" type="image/png" sizes="48x48" href="{% static 'img/favicon_48x48.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'img/favicon_192x192.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/desktop.css' %}">
    <link rel="stylesheet" href="{% static 'css/mobile.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
  {% block content %}{% endblock %}
</html>

src/sga/templates/form_simple.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}{{ form_name }}{% endblock %}

{% block main %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">{{ form_name }}</button>
  <a class="btn btn-secondary" href="{{ request.META.HTTP_REFERER }}">Cancelar</a>
</form>
{% endblock %}

src/sga/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body class="d-flex">
  <nav id="nav" class="d-flex bg-body border gap-3 flex-shrink-0">
    <a id="unexca-logo" class="d-flex justify-content-center mt-3 mx-4 mb-0" href="{% url 'home' %}">
      <img src="{% static 'img/unexca_logo_positivo_simple.webp' %}" alt="logo unexca" class="w-100">
    </a>
    <div class="nav nav-pills flex-column flex-grow-1 w-100 px-3 gap-1">
      {% if user.rol == 2 %}
      {% include 'user/teacher/navbar.html' %}
      {% endif %}

      {% if user.rol == 3 %}
      {% include 'user/student/navbar.html' %}
      {% endif %}

      <a class="nav-link{% if '/perfil' in request.path %} active{% endif %} nav-pill-profile" aria-current="page" href="{% url 'perfil' %}">
        <i class="bi bi-person{% if '/perfil' in request.path %}-fill{% endif %}"></i><span>Mi perfil</span>
      </a>
    </div>
    <a id="user-info" href="{% url 'perfil' %}" class="user-info d-flex w-100 p-3 gap-3 text-body text-decoration-none bg-body-subtle border-top">
      <div class="user-info-imagebox d-flex overflow-hidden bg-body-secondary border border-secondary-subtle rounded-circle" style="width: 3rem; height: 3rem">
        <img src="{% static 'img/avatar_default.webp' %}" alt="user avatar" class="img-fluid object-fit-cover">
      </div>
      <div class="user-info-textbox d-flex flex-column overflow-hidden" style="width: calc(100% - 4rem)">
        <span class="user-name fw-bold text-truncate">{{ user }}</span>
        <span class="user-role">{{ user.get_rol_display }}</span>
      </div>
    </a>
  </nav>
  <main class="p-3 bg-body">
    {% block main %}{% endblock %}
  </main>
</body>
{% endblock %}

src/sga/templates/profile.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Mi Perfil{% endblock %}

{% block main %}
<div class="d-flex flex-column gap-2">
  <form class="d-grid gap-2" action="">
    <div class="row row-gap-2">
      <div class="col-lg">
        <div class="input-group">
          <label class="input-group-text" for="username">Cédula</label>
          <input type="number" name="username" class="form-control" value="{{ user.username }}" disabled>
        </div>
      </div>
      <div class="col-lg">
        <div class="input-group">
          <label for="role_id" class="input-group-text">Rol</label>
          <input type="text" name="role_id" class="form-control" value="{{ user.get_rol_display }}" disabled>
        </div>
      </div>
    </div>
    <div class="row row-gap-2">
      <div class="col-lg">
        <div class="input-group">
          <label for="last_name" class="input-group-text">Apellidos</label>
          <input type="text" name="last_name" class="form-control" value="{{ user.last_name }}" disabled>
        </div>
      </div>
      <div class="col-lg">
        <div class="input-group">
          <label for="first_name" class="input-group-text">Nombres</label>
          <input name="first_name" type="text" class="form-control" value="{{ user.first_name }}" disabled>
        </div>
      </div>
    </div>
    <div class="row row-gap-2">
      <div class="col-lg">
        <div class="input-group">
          <label for="email" class="input-group-text">Correo</label>
          <input name="email" type="email" class="form-control" value="{{ user.email }}" required>
        </div>
      </div>
      <div class="col-md">
        <div class="input-group">
          <label for="telefono" class="input-group-text">Telefono</label>
          <input name="telefono" type="tel" class="form-control" minlength=11 maxlength=11 value="{{ user.datosusuario.telefono }}">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="input-group">
        <label for="direccion" class="input-group-text">Dirección</label>
        <input name="direccion" type="text" class="form-control" value="{{ user.datosusuario.direccion }}">
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Guardar</button>
  </form>
  <a class="btn btn-danger" href="{% url 'logout' %}" role="button">Cerrar sesión</a>
</div>
{% endblock %}

src/sga/templates/user/student/classes.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Mis clases{% endblock %}

{% block main %}
{% if inscripcion_list %}
<div class="accordion">
  {% for inscripcion in inscripcion_list %}
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="panelsStayOpen-collapse{{ forloop.counter }}">
        {{ inscripcion.clase.materia }} ({{ inscripcion.clase.seccion }})
      </button>
    </h2>
    <div id="panelsStayOpen-collapse{{ forloop.counter }}" class="accordion-collapse collapse">
      <div class="accordion-body">
        <table>
          <tr>
            <td class="fw-bold pe-3">Profesor</td>
            <td>{{ inscripcion.clase.docente }}</td>
          </tr>
          <tr>
            <td class="fw-bold pe-3">Teléfono</td>
            <td>{{ inscripcion.clase.docente.get_telefono }}</td>
          </tr>
          <tr>
            <td class="fw-bold pe-3">Correo</td>
            <td>{{ inscripcion.clase.docente.get_correo }}</td>
          </tr>
          <tr>
            <td class="fw-bold pe-3">Horario</td>
            <td>{{ inscripcion.clase.get_dia_display }} {{ inscripcion.clase.hora_inicio|time:"g:i A" }} - {{ inscripcion.clase.hora_fin|time:"g:i A" }}</td>
          </tr>
          <tr>
            <td class="fw-bold pe-3">Aula</td>
            <td>{{ inscripcion.clase.aula }}</td>
          </tr>
        </table>
        <form class='mt-2' action="{% url 'alumno_retirar_clase' inscripcion.id %}" method="post">
          {% csrf_token %}
          <button class="btn btn-danger btnEliminar">Retirar clase</button>
        </form>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<p>No tienes clases inscritas</p>
{% endif %}
<div class="d-flex flex-nowrap mt-3">
  <a class="btn btn-success" href="{% url 'alumno_inscribir_clase' %}">Inscribir clase</a>
</div>
<script src="{% static 'js/confirmacion.js' %}"></script>
{% endblock %}

src/sga/templates/user/student/navbar.html
<a href="{% url 'alumno_clases' %}"
  {% if '/u/3/clases/' in request.path %}
  class="nav-link active" aria-current="page"
  {% else %}
  class="nav-link"
  {% endif %}>
  <i class="bi bi-book{% if '/u/3/clases/' in request.path %}-fill{% endif %}"></i>
  <span>Mis clases</span>
</a>

<a href="{% url 'alumno_solicitudes' %}"
  {% if '/u/3/solicitudes/' in request.path %}
  class="nav-link active" aria-current="page"
  {% else %}
  class="nav-link"
  {% endif %}>
  <i class="bi bi-clipboard{% if '/u/3/solicitudes/' in request.path %}-fill{% endif %}"></i>
  <span>Solicitudes</span>
</a>

src/sga/templates/user/student/requests.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Solicitudes{% endblock %}

{% block main %}
<h2>Solicitudes</h2>
{% endblock %}

src/sga/templates/user/teacher/classes.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Mis clases{% endblock %}

{% block main %}
{% if clase_list %}
<div class="accordion">
  {% for clase in clase_list %}
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="panelsStayOpen-collapse{{ forloop.counter }}">{{ clase.materia }} - {{ clase.seccion }}</button>
    </h2>
    <div id="panelsStayOpen-collapse{{ forloop.counter }}" class="accordion-collapse collapse">
      <div class="accordion-body">
        <table>
          <tr>
            <td class="fw-bold pe-3">Sección</td>
            <td>{{ clase.seccion }}</td>
          </tr>
          <tr>
            <td class="fw-bold pe-3">Horario</td>
            <td>{{ clase.get_dia_display }} {{ clase.hora_inicio|time:"g:i A" }} - {{ clase.hora_fin|time:"g:i A" }}</td>
          </tr>
          <tr>
            <td class="fw-bold pe-3">Aula</td>
            <td>{{ clase.aula }}</td>
          </tr>
        </table>
        <a href="{% url 'docente_matricula_clase' clase.id %}" class="btn btn-primary mt-2">Ver matrícula</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<p>Usted no tiene clases asignadas</p>
{% endif %}
{% endblock %}

src/sga/templates/user/teacher/enrollments.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Mi matrícula{% endblock %}

{% block main %}
{% if not clases %}
<p>No posee clases asignadas</p>
{% else %}
<button class="btn btn-secondary dropdown-toggle mb-2" type="button" data-bs-toggle="dropdown" aria-expanded="false">{{ clase_display }}</button>
<ul class="dropdown-menu">
  {% for clase in clases %}
  <li><a class="dropdown-item {% if clase_id == clase.id %}active{% endif %}" href="{% url 'docente_matricula_clase' clase.id %}">{{ clase.materia }} ({{ clase.seccion }})</a></li>
  {% endfor %}
</ul>

{% if clase_id %}
{% if not inscripcion_list %}
<p>No tiene matrícula inscrita</p>
{% else %}
<table class="table">
  <tr>
    <th>#</th>
    <th>Cédula</th>
    <th>Apellidos</th>
    <th>Nombres</th>
    <th>Teléfono</th>
    <th>Correo</th>
  </tr>
  {% for inscripcion in inscripcion_list %}
  <tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ inscripcion.alumno.username }}</td>
    <td>{{ inscripcion.alumno.last_name }}</td>
    <td>{{ inscripcion.alumno.first_name }}</td>
    <td>{{ inscripcion.alumno.get_telefono }}</td>
    <td>{{ inscripcion.alumno.get_correo }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}
{% endif %}
{% endif %}
{% endblock %}

src/sga/templates/user/teacher/navbar.html
<a href="{% url 'docente_clases' %}"
  {% if '/u/2/clases/' in request.path %}
  class="nav-link active" aria-current="page"
  {% else %}
  class="nav-link"
  {% endif %}>
  <i class="bi bi-book{% if "/u/2/clases/" in request.path %}-fill{% endif %}"></i>
  <span>Mis clases</span>
</a>

<a href="{% url 'docente_matricula' %}"
  {% if '/u/2/matricula/' in request.path %}
  class="nav-link active" aria-current="page"
  {% else %}
  class="nav-link"
  {% endif %}>
  <i class="bi bi-people{% if "/u/2/matricula/" in request.path %}-fill{% endif %}"></i>
  <span>Mi matrícula</span>
</a>